# How to use :
# auth_password=123456 sudo_password=123456 uid=1000 gid=1000 docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

services:
  code-server:
    image: expm02/vscode-web-docker:latest
    container_name: docker_vscode_web
    # build: 
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=Asia/Shanghai
      - PASSWORD=${auth_password}
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${sudo_password}
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/workspace #optional
    volumes:
      - ./volumes/config/:/config/
      - ./volumes/workspace/:/workspace/
    ports:
      - 8090:8443
    networks: 
      vpn:
        ipv4_address: 172.168.26.2
    restart: unless-stopped


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.26.0/24
          gateway: 172.168.26.1
    